/**
 * UI strings, English and French. Content coming from the API (event names, taglines, questions, categories...)
 * is NOT in here: it is localised with i18n.pick().
 *
 * Keys are used as t('group.key'). Plural keys: key_one / key_other (called with {count}).
 */

export const en = {
  common: {
    play: 'Play',
    scoreboard: 'Scoreboard',
    live: 'Live',
    powered: 'Powered by',
    all_events: 'All events',
    retry: 'Try again',
    refresh: 'Refresh',
    optional: 'optional',
  },
  a11y: {
    skip: 'Skip to content',
    language: 'Language',
  },
  lang: { en: 'English', fr: 'Français' },
  theme: { label: 'Theme', system: 'System', light: 'Light', dark: 'Dark' },

  hub: {
    page_title: 'Gravitee Quiz Events',
    eyebrow: 'Live events',
    title_em: 'Quiz Events',
    tagline: 'Pick your event, answer fast and climb the live leaderboard.',
    empty_title: 'No live event right now',
    empty_text: 'New events show up here as soon as they go live. Come back soon!',
    error_title: 'We could not load the events',
    error_text: 'Check your connection and try again.',
    loaded_one: '{count} live event',
    loaded_other: '{count} live events',
  },

  notfound: {
    page_title: 'Page not found · Gravitee Quiz Events',
    title: 'Page not found',
    text: 'The page you are looking for does not exist or has moved.',
    cta: 'See live events',
  },

  event: {
    not_found_title: 'We could not find this event',
    not_found_text: 'The link may be mistyped, or the event is not open yet.',
    see_events: 'See live events',
    error_title: 'We could not load this event',
    error_text: 'Check your connection and try again.',
    draft_title: 'Preview: draft event',
    draft_text: 'This event is not public yet. Only signed-in admins can see this page.',
    closed_badge: 'Ended',
    closed_title: 'This event has ended',
    closed_text: 'Thanks to everyone who played! The final scoreboard is still online.',
  },

  landing: {
    hero_default: 'Become THE {title}!',
    play: 'Play now',
    scoreboard: 'Scoreboard',
    topics: 'Topics',
    stat_questions: 'Questions',
    stat_seconds: 'Seconds each',
    stat_players: 'Players so far',
    players_live: 'Live',
    keys_hint: 'Playing on a keyboard? Press G for green and R for red.',
    resume_title: 'Game in progress',
    resume_text: 'You were on question {n} of {total}. Pick up where you left off.',
    resume: 'Resume game',
    discard: 'Start over',
  },

  reg: {
    title: 'Who is playing?',
    subtitle: 'Your score lands on the leaderboard under your name.',
    first_name: 'First name',
    last_name: 'Last name',
    email: 'Email',
    phone: 'Phone number',
    privacy: 'The public scoreboard only shows your first name and the initial of your last name. Your email and phone number stay private.',
    submit: 'Continue',
    back: 'Back',
    err: {
      first_name: 'Enter your first name.',
      last_name: 'Enter your last name.',
      name_email: 'Please enter your name, not your email address.',
      name_letters: 'Your name needs at least one letter.',
      name_chars: 'Your name contains characters we cannot accept, such as < or >.',
      email: 'Enter a valid email address, like name@company.com.',
      phone: 'Enter a valid phone number (6 to 15 digits).',
      phone_required: 'Enter your phone number.',
      consent: 'Please accept to continue.',
      too_long: 'This is too long.',
      server_field: 'Please check this field.',
      summary: 'Please fix the highlighted fields.',
    },
  },

  rules: {
    title: 'How to play',
    subtitle_named: 'Ready, {name}? Here is what to expect.',
    subtitle: 'Here is what to expect.',
    questions_title_one: '{count} question',
    questions_title_other: '{count} questions',
    questions_text: 'One at a time. Each has a green answer and a red answer: pick the right one.',
    time_title_one: '{count} second each',
    time_title_other: '{count} seconds each',
    time_text: 'The clock starts the moment a question appears. No answer in time means no points.',
    score_title: 'Fast answers score more',
    score_correct: 'A correct answer earns {points} points.',
    score_bonus: 'Answer quickly to collect up to {bonus} bonus points.',
    score_wrong: 'A wrong answer earns {points} points.',
    score_none: 'Unanswered questions earn nothing.',
    controls_title: 'Green or red',
    controls_text: 'Tap a button, press G or R on a keyboard, or hit a Bluetooth buzzer.',
    controls_text_touch: 'Tap the green or the red button.',
    green: 'Green',
    red: 'Red',
    buzzer_title: 'Playing with buzzers?',
    buzzer_none: 'No buzzer connected yet. Taps and keys always work.',
    buzzer_one: 'One buzzer connected.',
    buzzer_both: 'Both buzzers connected. Ready!',
    buzzer_connect: 'Connect buzzers',
    buzzer_manage: 'Manage buzzers',
    start: 'Start the game',
    note: 'The first question starts the clock right away.',
    back: 'Back',
    err_not_enough: 'This event does not have enough questions yet. Please tell the event team.',
    err_closed: 'This event has just ended.',
    err_network: 'We could not reach the server. Check your connection and try again.',
    err_server: 'The server is having a moment. Please try again in a few seconds.',
    err_generic: 'Something went wrong. Please try again.',
    err_title: 'We could not start your game',
  },

  game: {
    question: 'Question',
    progress: 'Question {n} of {total}',
    time_left: 'Time left',
    seconds_left_one: '{count} second left',
    seconds_left_other: '{count} seconds left',
    locked: 'Answer locked in',
    locked_aria: 'Answer locked in: {answer}',
    timeout: 'Time is up',
    timeout_aria: 'Time is up. No answer recorded.',
    category_none: 'General',
    media_alt: 'Illustration for this question',
    answer_green: 'Green answer:',
    answer_red: 'Red answer:',
    saving_title: 'Saving your score…',
    saving_keep: 'Your answers are safe on this screen. Please keep this page open.',
    saving_retry: 'Connection trouble. Trying again in {s}s (attempt {n}).',
    saving_retry_now: 'Try again now',
    saving_sending: 'Sending your answers (attempt {n})…',
    failed_title: 'We could not save your score',
    failed_text: 'Your answers are still on this screen. Try again, or ask the event team for help.',
    failed_closed: 'The event ended before your score could be saved.',
    saved_title: 'Your score is already saved',
    saved_text: 'This game was already submitted. You can find your score on the scoreboard.',
  },

  results: {
    score: 'Your score',
    points: 'points',
    rank: 'Rank #{rank} of {total}',
    rank_aria: 'Rank {rank} of {total} players',
    correct: 'Correct',
    wrong: 'Wrong',
    unanswered: 'Unanswered',
    summary: '{correct} correct, {wrong} wrong, {unanswered} unanswered.',
    announce: 'Your score: {score} points. Rank {rank} of {total}.',
    review: 'Review answers',
    scoreboard: 'View scoreboard',
    again: 'Play again',
    next_player: 'Next player in {s}s',
    msg_perfect: 'Flawless!',
    msg_perfect_named: 'Flawless, {name}!',
    msg_great: 'Outstanding!',
    msg_great_named: 'Outstanding, {name}!',
    msg_good: 'Great game!',
    msg_good_named: 'Great game, {name}!',
    msg_ok: 'Not bad at all!',
    msg_ok_named: 'Not bad at all, {name}!',
    msg_start: 'Good start!',
    msg_start_named: 'Good start, {name}!',
    sub_perfect: 'Every single answer was right. Legendary.',
    sub_great: 'You really know your stuff.',
    sub_good: 'A solid score. Can you beat it?',
    sub_ok: 'Review your answers to level up.',
    sub_start: 'Check the explanations and give it another go.',
    sub_first: 'You are leading the board right now!',
    sub_podium: 'You are on the podium!',
  },

  review: {
    title: 'Review your answers',
    subtitle: 'Here is how every question went.',
    back: 'Back to results',
    filter_label: 'Show',
    filter_all: 'All ({count})',
    filter_wrong: 'Mistakes only ({count})',
    your_answer: 'Your answer',
    correct_answer: 'Correct answer',
    no_answer: 'No answer',
    explanation: 'Why',
    points: 'points',
    state_correct: 'Correct',
    state_wrong: 'Wrong',
    state_missed: 'Unanswered',
    empty_wrong: 'No mistakes. What a game!',
    seconds: '{s}s',
  },


};

export const fr = {
  common: {
    play: 'Jouer',
    scoreboard: 'Classement',
    live: 'En direct',
    powered: 'Propulsé par',
    all_events: 'Tous les événements',
    retry: 'Réessayer',
    refresh: 'Actualiser',
    optional: 'facultatif',
  },
  a11y: {
    skip: 'Aller au contenu',
    language: 'Langue',
  },
  lang: { en: 'English', fr: 'Français' },
  theme: { label: 'Thème', system: 'Système', light: 'Clair', dark: 'Sombre' },

  hub: {
    page_title: 'Gravitee Quiz Events',
    eyebrow: 'Événements en direct',
    title_em: 'Quiz Events',
    tagline: 'Choisissez votre événement, répondez vite et grimpez dans le classement en direct.',
    empty_title: 'Aucun événement en direct pour le moment',
    empty_text: 'Les nouveaux événements apparaissent ici dès qu’ils démarrent. Revenez bientôt !',
    error_title: 'Impossible de charger les événements',
    error_text: 'Vérifiez votre connexion puis réessayez.',
    loaded_one: '{count} événement en direct',
    loaded_other: '{count} événements en direct',
  },

  notfound: {
    page_title: 'Page introuvable · Gravitee Quiz Events',
    title: 'Page introuvable',
    text: 'La page que vous cherchez n’existe pas ou a été déplacée.',
    cta: 'Voir les événements en direct',
  },

  event: {
    not_found_title: 'Événement introuvable',
    not_found_text: 'Le lien est peut-être erroné, ou l’événement n’est pas encore ouvert.',
    see_events: 'Voir les événements en direct',
    error_title: 'Impossible de charger cet événement',
    error_text: 'Vérifiez votre connexion puis réessayez.',
    draft_title: 'Aperçu : événement en brouillon',
    draft_text: 'Cet événement n’est pas encore public. Seuls les admins connectés voient cette page.',
    closed_badge: 'Terminé',
    closed_title: 'Cet événement est terminé',
    closed_text: 'Merci à tous les joueurs ! Le classement final reste en ligne.',
  },

  landing: {
    hero_default: 'Devenez LE {title} !',
    play: 'Jouer maintenant',
    scoreboard: 'Classement',
    topics: 'Thèmes',
    stat_questions: 'Questions',
    stat_seconds: 'Secondes chacune',
    stat_players: 'Joueurs jusqu’ici',
    players_live: 'En direct',
    keys_hint: 'Sur un clavier ? Appuyez sur G pour le vert et sur R pour le rouge.',
    resume_title: 'Partie en cours',
    resume_text: 'Vous étiez à la question {n} sur {total}. Reprenez où vous vous êtes arrêté.',
    resume: 'Reprendre la partie',
    discard: 'Recommencer',
  },

  reg: {
    title: 'Qui joue ?',
    subtitle: 'Votre score apparaît dans le classement sous votre nom.',
    first_name: 'Prénom',
    last_name: 'Nom',
    email: 'Email',
    phone: 'Numéro de téléphone',
    privacy: 'Le classement public n’affiche que votre prénom et l’initiale de votre nom. Votre email et votre téléphone restent privés.',
    submit: 'Continuer',
    back: 'Retour',
    err: {
      first_name: 'Saisissez votre prénom.',
      last_name: 'Saisissez votre nom.',
      name_email: 'Saisissez votre nom, pas votre adresse email.',
      name_letters: 'Votre nom doit contenir au moins une lettre.',
      name_chars: 'Votre nom contient des caractères non acceptés, comme < ou >.',
      email: 'Saisissez une adresse email valide, par exemple nom@entreprise.com.',
      phone: 'Saisissez un numéro de téléphone valide (6 à 15 chiffres).',
      phone_required: 'Saisissez votre numéro de téléphone.',
      consent: 'Veuillez accepter pour continuer.',
      too_long: 'Ce champ est trop long.',
      server_field: 'Veuillez vérifier ce champ.',
      summary: 'Veuillez corriger les champs signalés.',
    },
  },

  rules: {
    title: 'Comment jouer',
    subtitle_named: 'Prêt à jouer, {name} ? Voici ce qui vous attend.',
    subtitle: 'Voici ce qui vous attend.',
    questions_title_one: '{count} question',
    questions_title_other: '{count} questions',
    questions_text: 'Une à la fois. Chacune a une réponse verte et une réponse rouge : choisissez la bonne.',
    time_title_one: '{count} seconde chacune',
    time_title_other: '{count} secondes chacune',
    time_text: 'Le chrono démarre dès qu’une question apparaît. Pas de réponse à temps, pas de points.',
    score_title: 'Les réponses rapides rapportent plus',
    score_correct: 'Une bonne réponse rapporte {points} points.',
    score_bonus: 'Répondez vite pour gagner jusqu’à {bonus} points bonus.',
    score_wrong: 'Une mauvaise réponse rapporte {points} points.',
    score_none: 'Une question sans réponse ne rapporte rien.',
    controls_title: 'Vert ou rouge',
    controls_text: 'Touchez un bouton, appuyez sur G ou R au clavier, ou utilisez un buzzer Bluetooth.',
    controls_text_touch: 'Touchez le bouton vert ou le bouton rouge.',
    green: 'Vert',
    red: 'Rouge',
    buzzer_title: 'Vous jouez avec des buzzers ?',
    buzzer_none: 'Aucun buzzer connecté pour l’instant. Le toucher et le clavier fonctionnent toujours.',
    buzzer_one: 'Un buzzer connecté.',
    buzzer_both: 'Les deux buzzers sont connectés. Prêt !',
    buzzer_connect: 'Connecter les buzzers',
    buzzer_manage: 'Gérer les buzzers',
    start: 'Lancer la partie',
    note: 'La première question démarre le chrono immédiatement.',
    back: 'Retour',
    err_not_enough: 'Cet événement n’a pas encore assez de questions. Prévenez l’équipe de l’événement.',
    err_closed: 'Cet événement vient de se terminer.',
    err_network: 'Impossible de joindre le serveur. Vérifiez votre connexion puis réessayez.',
    err_server: 'Le serveur est momentanément indisponible. Réessayez dans quelques secondes.',
    err_generic: 'Une erreur est survenue. Veuillez réessayer.',
    err_title: 'Impossible de démarrer votre partie',
  },

  game: {
    question: 'Question',
    progress: 'Question {n} sur {total}',
    time_left: 'Temps restant',
    seconds_left_one: '{count} seconde restante',
    seconds_left_other: '{count} secondes restantes',
    locked: 'Réponse verrouillée',
    locked_aria: 'Réponse verrouillée : {answer}',
    timeout: 'Temps écoulé',
    timeout_aria: 'Temps écoulé. Aucune réponse enregistrée.',
    category_none: 'Général',
    media_alt: 'Illustration de la question',
    answer_green: 'Réponse verte :',
    answer_red: 'Réponse rouge :',
    saving_title: 'Enregistrement de votre score…',
    saving_keep: 'Vos réponses sont conservées sur cet écran. Gardez cette page ouverte.',
    saving_retry: 'Problème de connexion. Nouvel essai dans {s} s (tentative {n}).',
    saving_retry_now: 'Réessayer maintenant',
    saving_sending: 'Envoi de vos réponses (tentative {n})…',
    failed_title: 'Impossible d’enregistrer votre score',
    failed_text: 'Vos réponses sont toujours sur cet écran. Réessayez, ou demandez de l’aide à l’équipe.',
    failed_closed: 'L’événement s’est terminé avant l’enregistrement de votre score.',
    saved_title: 'Votre score est déjà enregistré',
    saved_text: 'Cette partie a déjà été envoyée. Retrouvez votre score dans le classement.',
  },

  results: {
    score: 'Votre score',
    points: 'points',
    rank: 'Rang #{rank} sur {total}',
    rank_aria: 'Rang {rank} sur {total} joueurs',
    correct: 'Bonnes',
    wrong: 'Fausses',
    unanswered: 'Sans réponse',
    summary: '{correct} bonnes, {wrong} fausses, {unanswered} sans réponse.',
    announce: 'Votre score : {score} points. Rang {rank} sur {total}.',
    review: 'Revoir les réponses',
    scoreboard: 'Voir le classement',
    again: 'Rejouer',
    next_player: 'Joueur suivant dans {s} s',
    msg_perfect: 'Sans faute !',
    msg_perfect_named: 'Sans faute, {name} !',
    msg_great: 'Impressionnant !',
    msg_great_named: 'Impressionnant, {name} !',
    msg_good: 'Belle partie !',
    msg_good_named: 'Belle partie, {name} !',
    msg_ok: 'Pas mal du tout !',
    msg_ok_named: 'Pas mal du tout, {name} !',
    msg_start: 'Bon début !',
    msg_start_named: 'Bon début, {name} !',
    sub_perfect: 'Toutes les réponses étaient justes. Légendaire.',
    sub_great: 'Vous maîtrisez vraiment le sujet.',
    sub_good: 'Un solide score. Saurez-vous le battre ?',
    sub_ok: 'Revoyez vos réponses pour progresser.',
    sub_start: 'Lisez les explications et retentez votre chance.',
    sub_first: 'Vous êtes en tête du classement en ce moment !',
    sub_podium: 'Vous êtes sur le podium !',
  },

  review: {
    title: 'Revoir vos réponses',
    subtitle: 'Voici comment s’est passée chaque question.',
    back: 'Retour aux résultats',
    filter_label: 'Afficher',
    filter_all: 'Toutes ({count})',
    filter_wrong: 'Erreurs seulement ({count})',
    your_answer: 'Votre réponse',
    correct_answer: 'Bonne réponse',
    no_answer: 'Pas de réponse',
    explanation: 'Pourquoi',
    points: 'points',
    state_correct: 'Correct',
    state_wrong: 'Faux',
    state_missed: 'Sans réponse',
    empty_wrong: 'Aucune erreur. Quelle partie !',
    seconds: '{s} s',
  },


};
