/**
 * strings.js - EN / FR dictionaries of the scoreboard (shared/js/i18n.js format: nested keys, {placeholders},
 * `_one` / `_other` plural suffixes selected by a `count` param). French keeps the non-breaking space before ? ! : ;
 */
const NB = ' ';

export const dictionaries = {
  en: {
    a11y: {
      skip: 'Skip to the leaderboard',
      board: 'Leaderboard',
      podium: 'Top three players',
      ranks: 'Ranks {from} to {to}',
      stats: 'Statistics',
    },
    common: { powered: 'Powered by', scoreboard: 'Scoreboard' },
    controls: {
      group: 'Display options',
      language: 'Language',
      theme: 'Theme',
      system: 'System',
      light: 'Light',
      dark: 'Dark',
      fullscreen: 'Enter full screen',
      fullscreen_exit: 'Exit full screen',
    },
    status: {
      connecting: 'Connecting…',
      live: 'Live',
      live_poll: 'Live, refreshing every {s} s',
      reconnecting: 'Reconnecting…',
      closed: 'Final results',
      draft: 'Draft preview',
      loading: 'Connecting to the live scoreboard…',
      error_title: 'Reconnecting…',
      error_text: 'We cannot reach the server right now. This screen retries automatically.',
      lost_title: 'Connection lost',
      lost_text: 'Showing the last known scores. Reconnecting…',
      restored: 'Live updates are back.',
      notfound_title: 'Event not found',
      notfound_text: 'This scoreboard does not exist, or the event is not published yet.',
      home: 'All events',
    },
    board: {
      ranks: 'Ranks {from} to {to}',
      open_spot: 'Open spot, could be you',
      your_name: 'Your name here',
      just_finished: 'Just finished',
      just_now: 'just now',
      points: 'points',
      correct_n_one: '{count} correct answer',
      correct_n_other: '{count} correct answers',
      wrong_n_one: '{count} wrong answer',
      wrong_n_other: '{count} wrong answers',
      rank_n: 'Rank {n}',
    },
    join: {
      title: 'Scan to play',
      text: 'Open your camera, scan the code and climb the leaderboard.',
      qr: 'QR code, opens {url}',
      play: 'Play now',
    },
    empty: {
      title: 'Be the first to play!',
      text_one: 'Scan the code, answer 1 quick question and take the #1 spot.',
      text_other: 'Scan the code, answer {count} quick questions and take the #1 spot.',
      text_noscan_one: 'Answer 1 quick question and take the #1 spot.',
      text_noscan_other: 'Answer {count} quick questions and take the #1 spot.',
      text_closed: 'This event has ended and no score was recorded.',
      title_closed: 'No scores recorded',
    },
    counters: {
      players_one: 'player',
      players_other: 'players',
      games_one: 'game played',
      games_other: 'games played',
    },
    stats: {
      title: 'The numbers so far',
      players: 'Players',
      games: 'Games played',
      top: 'Top score',
      top_sub: 'by {name}',
      accuracy: 'Best round',
      accuracy_sub: '{n} of {total} correct',
      rules_one: '{count} question',
      rules_other: '{count} questions',
      rules_time: '{s} s per question',
      rules_max: 'up to {p} points',
      categories: 'Categories',
    },
    live: {
      one: '{name} finished with {score} points and is now ranked {rank}.',
      many: '{count} new scores. Leader: {name} with {score} points.',
      leader: 'New leader: {name} with {score} points!',
    },
  },

  fr: {
    a11y: {
      skip: `Aller au classement`,
      board: 'Classement',
      podium: 'Les trois premiers joueurs',
      ranks: 'Rangs {from} à {to}',
      stats: 'Statistiques',
    },
    common: { powered: 'Propulsé par', scoreboard: 'Classement' },
    controls: {
      group: 'Options d’affichage',
      language: 'Langue',
      theme: 'Thème',
      system: 'Système',
      light: 'Clair',
      dark: 'Sombre',
      fullscreen: 'Passer en plein écran',
      fullscreen_exit: 'Quitter le plein écran',
    },
    status: {
      connecting: 'Connexion…',
      live: 'En direct',
      live_poll: `En direct, actualisation toutes les {s}${NB}s`,
      reconnecting: 'Reconnexion…',
      closed: 'Résultats finaux',
      draft: 'Aperçu brouillon',
      loading: 'Connexion au classement en direct…',
      error_title: 'Reconnexion…',
      error_text: 'Le serveur est injoignable pour le moment. Cet écran réessaie automatiquement.',
      lost_title: 'Connexion perdue',
      lost_text: 'Derniers scores connus affichés. Reconnexion…',
      restored: 'Les mises à jour en direct sont rétablies.',
      notfound_title: 'Événement introuvable',
      notfound_text: 'Ce classement n’existe pas, ou l’événement n’est pas encore publié.',
      home: 'Tous les événements',
    },
    board: {
      ranks: 'Rangs {from} à {to}',
      open_spot: `Place libre, et si c’était vous${NB}?`,
      your_name: 'Votre nom ici',
      just_finished: 'Vient de finir',
      just_now: 'à l’instant',
      points: 'points',
      correct_n_one: '{count} bonne réponse',
      correct_n_other: '{count} bonnes réponses',
      wrong_n_one: '{count} mauvaise réponse',
      wrong_n_other: '{count} mauvaises réponses',
      rank_n: 'Rang {n}',
    },
    join: {
      title: 'Scannez pour jouer',
      text: 'Ouvrez votre appareil photo, scannez le code et grimpez au classement.',
      qr: 'QR code, ouvre {url}',
      play: 'Jouer',
    },
    empty: {
      title: `Soyez le premier à jouer${NB}!`,
      text_one: `Scannez le code, répondez à 1 question éclair et prenez la 1re place.`,
      text_other: `Scannez le code, répondez à {count} questions éclair et prenez la 1re place.`,
      text_noscan_one: `Répondez à 1 question éclair et prenez la 1re place.`,
      text_noscan_other: `Répondez à {count} questions éclair et prenez la 1re place.`,
      text_closed: 'Cet événement est terminé et aucun score n’a été enregistré.',
      title_closed: 'Aucun score enregistré',
    },
    counters: {
      players_one: 'joueur',
      players_other: 'joueurs',
      games_one: 'partie jouée',
      games_other: 'parties jouées',
    },
    stats: {
      title: 'Les chiffres du moment',
      players: 'Joueurs',
      games: 'Parties jouées',
      top: 'Meilleur score',
      top_sub: 'par {name}',
      accuracy: 'Meilleure manche',
      accuracy_sub: '{n} bonnes réponses sur {total}',
      rules_one: '{count} question',
      rules_other: '{count} questions',
      rules_time: `{s}${NB}s par question`,
      rules_max: 'jusqu’à {p} points',
      categories: 'Catégories',
    },
    live: {
      one: '{name} a terminé avec {score} points et se classe au rang {rank}.',
      many: '{count} nouveaux scores. En tête : {name} avec {score} points.',
      leader: 'Nouveau leader : {name} avec {score} points !',
    },
  },
};
