#!/usr/bin/env node
// Regenerates shared/icons/sprite.svg from tools/icons.json using Phosphor Icons core (MIT).
//
//   node shared/tools/build-sprite.mjs [--src <dir containing regular/ fill/ bold/ ...>] [--out icons/sprite.svg]
//
// Without --src the script runs `npm pack @phosphor-icons/core` into a temp dir and extracts it.
import { readFileSync, writeFileSync, mkdtempSync, existsSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(`--${n}`); return i >= 0 ? args[i + 1] : d; };
const out = resolve(opt('out', join(here, '..', 'icons', 'sprite.svg')));
let src = opt('src');

if (!src) {
  const tmp = mkdtempSync(join(tmpdir(), 'phosphor-'));
  console.log('npm pack @phosphor-icons/core ...');
  const tgz = execFileSync('npm', ['pack', '@phosphor-icons/core', '--silent', '--pack-destination', tmp], { encoding: 'utf8' }).trim().split('\n').pop();
  execFileSync('tar', ['-xzf', join(tmp, tgz), '-C', tmp]);
  src = join(tmp, 'package', 'assets');
}
if (!existsSync(join(src, 'regular'))) throw new Error(`Not a Phosphor assets dir: ${src}`);

const { icons } = JSON.parse(readFileSync(join(here, 'icons.json'), 'utf8'));
const symbols = [];
const seen = new Set();
const missing = [];
for (const spec of icons) {
  let [nameAndWeight, alias] = spec.split('=');
  const [name, weight = 'regular'] = nameAndWeight.split(':');
  const id = alias || (weight === 'regular' ? name : `${name}-${weight}`);
  if (seen.has(id)) continue;
  seen.add(id);
  const file = join(src, weight, weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`);
  if (!existsSync(file)) { missing.push(`${id} (${file})`); continue; }
  const svg = readFileSync(file, 'utf8');
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? '0 0 256 256';
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  symbols.push(`<symbol id="${id}" viewBox="${viewBox}">${inner}</symbol>`);
}
if (missing.length) { console.error('Missing icons:\n  ' + missing.join('\n  ')); process.exit(1); }

const header = `<!-- Generated by shared/tools/build-sprite.mjs from Phosphor Icons core (MIT, https://phosphoricons.com). Do not edit by hand. ${symbols.length} symbols. -->`;
const svg = `<svg xmlns="http://www.w3.org/2000/svg">\n${header}\n${symbols.join('\n')}\n</svg>\n`;
writeFileSync(out, svg);
console.log(`wrote ${out}: ${symbols.length} symbols, ${(svg.length / 1024).toFixed(1)} KB`);
